name: PR build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Check environment
        run: |
          echo "java: $( java -version )"
          echo "gradle: $( ./gradlew --version )"
      - name: Build
        run: ./gradlew clean build test check javadoc
